export const productList = [
  {
    _id: 1,
    mainProduct: true,
    type: 'roll',
    name: 'Black sharks',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 100,
  },
  {
    _id: 2,
    mainProduct: true,
    type: 'roll',
    name: 'segun',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 100,
  },
  {
    _id: 3,
    mainProduct: true,
    type: 'roll',
    name: 'segun',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 120,
  },
  {
    _id: 4,
    mainProduct: true,
    type: 'pizza',
    name: 'Блек шарк пица',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 130,
  },
  {
    _id: 5,
    mainProduct: true,
    type: 'roll',
    name: 'Black sharks',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 100,
  },
  {
    _id: 6,
    mainProduct: true,
    type: 'roll',
    name: 'segun',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 120,
  },
  {
    _id: 7,
    mainProduct: true,
    type: 'pizza',
    name: 'Блек шарк пица',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 130,
  },
  {
    _id: 8,
    mainProduct: true,
    type: 'roll',
    name: 'Black sharks',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 100,
  },
  {
    _id: 9,
    mainProduct: true,
    type: 'roll',
    name: 'segun',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 120,
  },
  {
    _id: 10,
    mainProduct: true,
    type: 'pizza',
    name: 'Блек шарк пица',
    about: 'Рис - Угорь - Огурец - Творожный сыр - Икра летучей рыбы',
    count: 1,
    price: 100,
    totalPrice: 130,
  },
];